data_path: output/generated_mols_spindr                # Path to the directory containing the generated molecules.
data_subdir: conditional                               # Subdirectory containing the generated molecules.
data_set: SPINDR                                       # Dataset to use for evaluation.
num_workers: 3                                         # Number of workers.
compute_drugflow_clashes: true                         # Whether to compute drugflow clashes.
compute_edm: true                                      # Whether to compute EDM metrics.
compute_novelty: true                                  # Whether to compute novelty.
compute_posebusters: true                              # Whether to compute posebusters metrics (slow).
compute_posecheck: true                                # Whether to compute posecheck.
compute_strain: true                                   # Whether to compute posecheck strain energies (slow).
compute_physchem: true                                 # Whether to compute physico-chemical properties.
compute_vina: true                                     # Whether to compute VINA scores.
add_hydrogens: false                                   # Whether to add hydrogens (necessary post-processing step for baseline models).