checkpoints_path: trained_models/best_spindr                # Path to the trained model weights.
output_path: output/generated_mols_spindr                   # Path to the output directory.
data_set: SPINDR                                            # Dataset to use for generation.
num_molecules: 100                                          # Number of molecules to generate.
chunk_size: 3                                               # Number of chunks to process in parallel.
max_atoms: 100                                              # Maximum number of atoms per molecule.
num_time_steps: 60                                          # Number of time steps for the flow matching integration.
time_step_spacing: linear                                   # Time step spacing method for the flow matching integration.
integration_method: euler_maruyama                          # Integration method for the flow matching integration.
cfg_factor: 0.5                                             # Classifier-free guidance factor.
fragment_type: null                                         # Fragment type for the fragment-based generation: null | largest | second_largest | smallest.
bond_predictor_dir: trained_models/bond_predictor/bp_spindr # Path to the bond predictor model.