checkpoints_path: logs/NEAT/version_121
output_path: output/version_121_cfg05_smallest
data_set: CrossDocked
num_molecules: 100
chunk_size: 3
max_atoms: 200
num_time_steps: 60
time_step_spacing: linear
integration_method: euler_maruyama
fragment_type: smallest  # null | largest | second_largest | smallest
