checkpoints_path: logs/NEAT/version_129
output_path: output/version_129_cfg05_null
data_set: SPINDR
num_molecules: 100
chunk_size: 3
max_atoms: 200
num_time_steps: 60
time_step_spacing: linear
integration_method: euler_maruyama
fragment_type: null  # null | largest | second_largest | smallest
bond_predictor_path: /data/sharedXL/projects/Daniel/NEAT-Cond-Dev/logs/BondPredictor/SPINDR/version_2/checkpoints/bond_predictor_SPINDR-epoch=37.ckpt
