accumulate_grad_batches: 4
batch_size: 64
bias: true
data_set: CrossDocked
dropout: 0.1
learning_rate: 5.0e-05
lr_decay_epochs: 2000
lr_min_ratio: 0.1
lr_warmup_epochs: 10
max_epochs: 2000
n_embd: 768
n_embd_fm: 1536
n_head: 12
n_layer: 12
n_layers_fm: 6
noise_std: 2.5
perturbation_fraction: 0.5
perturbation_std: 0.05
rope: false
time_step_resampling: 4
time_step_sampling: logit_normal
weight_decay: 1.0e-06
pretrained_model_path: "logs/NEAT/pretrained_geom"
cfg_dropout: 0.5
pocket_n_layer: 8
